# Generated by Django 6.0.2 on 2026-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='products_ca_name_693421_idx',
            old_name='products_ca_name_9546c8_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_name_9ff0a3_idx',
            old_name='products_pr_name_9bb5d5_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_c898cc_idx',
            old_name='products_pr_categor_4dbd34_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_demand__e40867_idx',
            old_name='products_pr_demand__2d976f_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
