# Generated by Django 6.0.2 on 2026-02-28 10:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_rename_products_ca_name_9546c8_idx_products_ca_name_693421_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OneTimeOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_cart_user_id_b645f9_idx',
            old_name='cart_cart_user_id_0d6766_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_cart_id_4bd8c3_idx',
            old_name='cart_cartit_cart_id_6d9f10_idx',
        ),
        migrations.AddField(
            model_name='onetimeorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onetimeorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.onetimeorder'),
        ),
        migrations.AddField(
            model_name='onetimeorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_order_items', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='onetimeorder',
            index=models.Index(fields=['user', 'status'], name='cart_onetim_user_id_c4835c_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimeorderitem',
            index=models.Index(fields=['order', 'product'], name='cart_onetim_order_i_a90f06_idx'),
        ),
    ]
