# Generated by Django 6.0.2 on 2026-02-28 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_ca_name_9546c8_idx_products_ca_name_693421_idx_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_user_id_2a19e8_idx',
            old_name='subscriptio_user_id_bcae03_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_product_f82db2_idx',
            old_name='subscriptio_product_180dc8_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_start_d_c2f4cd_idx',
            old_name='subscriptio_start_d_46f7e0_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionhistory',
            new_name='subscriptio_subscri_7e6268_idx',
            old_name='subscriptio_subscri_2f766b_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_index=True, default='DAILY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['frequency', 'status'], name='subscriptio_frequen_5babf6_idx'),
        ),
    ]
