# Generated by Django 6.0.2 on 2026-02-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_onetimeorder_onetimeorderitem_and_more'),
        ('payments', '0001_initial'),
        ('subscriptions', '0002_rename_subscriptio_user_id_bcae03_idx_subscriptio_user_id_2a19e8_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_01767a_idx',
            old_name='payments_pay_user_id_4237aa_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_subscri_b2eaa9_idx',
            old_name='payments_pay_subscri_d60744_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_paid_at_b40014_idx',
            old_name='payments_pay_paid_at_dff235_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='one_time_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cart.onetimeorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription'),
        ),
    ]
