# Generated by Django 6.0.2 on 2026-02-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS users_user_role_36d76d_idx ON users_user(role);",
            reverse_sql="DROP INDEX IF EXISTS users_user_role_36d76d_idx;",
        ),
    ]
