# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations


def ensure_profile_columns(apps, schema_editor):
    table_name = "users_user"
    existing_columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }
    if "phone_number" not in existing_columns:
        schema_editor.execute("ALTER TABLE users_user ADD COLUMN phone_number varchar(20) NOT NULL DEFAULT '';")
    if "address" not in existing_columns:
        schema_editor.execute("ALTER TABLE users_user ADD COLUMN address text NOT NULL DEFAULT '';")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_users_user_role_4d8a13_idx_users_user_role_36d76d_idx"),
    ]

    operations = [
        migrations.RunPython(ensure_profile_columns, migrations.RunPython.noop),
    ]

